/*
 * Copyright 2023 HM Revenue & Customs
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package uk.gov.hmrc.perftests.cis.simulations

import io.gatling.core.scenario.Simulation
import uk.gov.hmrc.performance.simulation.PerformanceTestRunner
import uk.gov.hmrc.perftests.cis.requests.AuthRequests._
import uk.gov.hmrc.perftests.cis.requests.LandingPagesRequests._
import uk.gov.hmrc.perftests.cis.requests.NilMonthlyReturnRequests._
import uk.gov.hmrc.perftests.cis.requests.PrepopulationRequests._
import uk.gov.hmrc.perftests.cis.requests.VerifySubcontractorRequests._
import uk.gov.hmrc.perftests.cis.requests.StandardMonthlyReturnRequests._
import uk.gov.hmrc.perftests.cis.requests.AddIndividualSubcontractorRequests._
import uk.gov.hmrc.perftests.cis.requests.AddPartnershipSubcontractorRequests._
import uk.gov.hmrc.perftests.cis.requests.AddCompanySubcontractorRequests._
import uk.gov.hmrc.perftests.cis.requests.AddTrustSubcontractorRequests._
import uk.gov.hmrc.perftests.cis.requests.AmendCompanySubcontractorRequests._
import uk.gov.hmrc.perftests.cis.requests.AmendIndividualSubcontractorRequests._
import uk.gov.hmrc.perftests.cis.requests.AmendPartnershipSubcontractor._
import uk.gov.hmrc.perftests.cis.requests.AmendTrustSubcontractorRequests._
import uk.gov.hmrc.perftests.cis.requests.AmendedReturnRequests._
import uk.gov.hmrc.perftests.cis.requests.DeleteSubcontractorRequests._
import uk.gov.hmrc.perftests.cis.requests.ManageClientDetailsRequests._
import uk.gov.hmrc.perftests.cis.requests.ManageContractorDetailsRequests._
import uk.gov.hmrc.perftests.cis.requests.UnmatchedAndInsufficientVerificationRequests._
import uk.gov.hmrc.perftests.cis.requests.ViewReturnsHistoryRequests._
import uk.gov.hmrc.perftests.cis.requests.ViewVerificationHistoryRequests._

class CisSimulation extends Simulation with PerformanceTestRunner {

  setup("org-landing-pages", "OLP ").withRequests(
    getAuthPage,
    postManageAuthPage("Organisation", "EZ10800"),
    getSession,
    getManageFrontend,
    getSignIntoCISPage,
    getSignIntoCISRouting,
    getCisReturnDashboardPage
  )

  setup("agent-landing-pages", "ALP ").withRequests(
    getAuthPage,
    postManageAuthPage("Agent", "123456"),
    getSession,
    getManageFrontend,
    getSignIntoCISPage,
    getSignIntoCISRouting,
    getRetrieveClientList,
    getStartRetrieveClientList,
    getFileMonthlyCISReturnsUnfilteredListPage,
    postFileMonthlyCISReturnsSearchPage("ER", "EZ10800"),
    getClientFilteredViewFileMonthlyCISReturnPage,
    getClientCisReturnDashboardPage,
    getRedirectManageCISReturnPage
//    getManageYourCISReturnPage
  )

  setup("manage-client-details", "MClD").withRequests(
    getClientDetails,
    getWhatIsYourClientReference,
    postWhatIsYourClientReference("TEST-REF"),
    getClientReferenceUpdated,
    getClientFilteredViewFileMonthlyCISReturnPage,
    getRemoveClientOptionPage,
    postRemoveClientOptionPage("true"),
    getClientRemoved
  )

  setup("manage-contractor-details", "MCoD").withRequests(
    getContractorDetailsRedirect,
    getContractorDetailsManageRedirect,
    getContractorDetailsInfoPage,
    getChangeContractorUTR,
    postChangeContractorUTR("1234567895"),
    getContractorDetailsInfoPage,
    getChangeContractorSchemeName,
    postChangeContractorSchemeName("Test Scheme"),
    getContractorDetailsInfoPage,
    getRemoveContractorSchemeNameOption,
    postRemoveContractorSchemeNameOption("true"),
    getContractorDetailsInfoPage,
    getChangeContractorEmailAddress,
    postChangeContractorEmailAddress("test_email@domain.com"),
    getContractorDetailsInfoPage,
    getRemoveContractorEmailOption,
    postRemoveContractorEmailOption("true"),
    getContractorDetailsInfoPage,
    postContractorDetailsInfoPage,
    getContractorDetailsUpdated
  )

  setup("standard-monthly-return", "SMRP")
    .withRequests(
      getFileYourMonthlyCISReturn,
      postFileYourMonthlyCISReturn,
      getWhichTaxMonthAndYearAreYouFilingAReturnFor,
      postWhichTaxMonthAndYearAreYouFilingAReturnFor,
      getSelectSubcontractors,
      getSelectAllSelectSubcontractors,
      getDeselectAllSelectSubcontractors,
      postSelectSubcontractors("31001", "31002"),
      getYouHaveUnverifiedSubcontractors,
      postYouHaveUnverifiedSubcontractors("false"),
      getYouHaveAddedDetailsForTwoSubcontractors,
      getHowMuchDidYouPayToFirstSubcontractorInTotal,
      postHowMuchDidYouPayToFirstSubcontractorInTotal("1000"),
      getHowMuchDidFirstSubcontractorPayInMaterialCosts,
      postHowMuchDidFirstSubcontractorPayInMaterialCosts("200"),
      getHowMuchTaxInTotalDidYouDeductFromFirstSubcontractor,
      postHowMuchTaxInTotalDidYouDeductFromFirstSubcontractor("25"),
      getCheckYourAnswersForFirstSubcontractor,
      getChangeHowMuchDidYouPayToFirstSubcontractorInTotal,
      postChangeHowMuchDidYouPayToFirstSubcontractorInTotal("2000"),
      getCheckYourAnswersForFirstSubcontractor,
      getChangeHowMuchDidFirstSubcontractorPayInMaterialCosts,
      postChangeHowMuchDidFirstSubcontractorPayInMaterialCosts("500"),
      getCheckYourAnswersForFirstSubcontractor,
      getChangeHowMuchTaxInTotalDidYouDeductFromFirstSubcontractor,
      postChangeHowMuchTaxInTotalDidYouDeductFromFirstSubcontractor("125"),
      getCheckYourAnswersForFirstSubcontractor,
      postCheckYourAnswersForFirstSubcontractor,
      getYouHaveAddedDetailsForTwoSubcontractors,
      getChangeFirstSubcontractorsDetails,
      getChangeHowMuchDidYouPayToFirstSubcontractorInTotalDetails,
      postChangeHowMuchDidYouPayToFirstSubcontractorInTotalDetails("5000"),
      getChangeFirstSubcontractorsDetails,
      getChangeHowMuchDidFirstSubcontractorPayInMaterialCostsDetails,
      postChangeHowMuchDidFirstSubcontractorPayInMaterialCostsDetails("1000"),
      getChangeFirstSubcontractorsDetails,
      getChangeHowMuchTaxInTotalDidYouDeductFromFirstSubcontractorDetails,
      postChangeHowMuchTaxInTotalDidYouDeductFromFirstSubcontractorDetails("250"),
      getChangeFirstSubcontractorsDetails,
      postChangeFirstSubcontractorsDetails,
      getHowMuchDidYouPayToSecondSubcontractorInTotal,
      postHowMuchDidYouPayToSecondSubcontractorInTotal("5000"),
      getHowMuchDidSecondSubcontractorPayInMaterialCosts,
      postHowMuchDidSecondSubcontractorPayInMaterialCosts("2000"),
      getHowMuchTaxInTotalDidYouDeductFromSecondSubcontractor,
      postHowMuchTaxInTotalDidYouDeductFromSecondSubcontractor("1000"),
      getCheckYourAnswersForSecondSubcontractor,
      postCheckYourAnswersForSecondSubcontractor,
      getYouHaveAddedDetailsForTwoSubcontractors,
      getAreYouSureYouWantToRemoveFirstSubcontractor,
      postAreYouSureYouWantToRemoveFirstSubcontractor("true"),
      getYouHaveAddedDetailsForASingleSubcontractor,
      postYouHaveAddedDetailsForASingleSubcontractor("false"),
      getSummaryOfPaymentsMade,
      getDoYouConfirmTheInformationInThisReturnIsCorrect,
      postDoYouConfirmTheInformationInThisReturnIsCorrect("true"),
      getDeclarationOfEmploymentStatus,
      postDeclarationOfEmploymentStatus("false"),
      getDeclarationOfVerifiedStatus,
      postDeclarationOfVerifiedStatus("false"),
      getSubmitInactivityRequest,
      postSubmitInactivityRequest("false"),
      getDoYouWantConfirmationByEmailThatThisReturnHasBeenSuccessfullySubmitted,
      postDoYouWantConfirmationByEmailThatThisReturnHasBeenSuccessfullySubmitted("false"),
      getCheckYourAnswersBeforeSubmittingYourReturn,
      getChangeDeclarationOfEmploymentStatus,
      postChangeDeclarationOfEmploymentStatus("true"),
      getCheckYourAnswersBeforeSubmittingYourReturn,
      getChangeDeclarationOfVerifiedStatus,
      postChangeDeclarationOfVerifiedStatus("true"),
      getCheckYourAnswersBeforeSubmittingYourReturn,
      getChangeSubmitInactivityRequest,
      postChangeSubmitInactivityRequest("true"),
      getInactivityRequest,
      getCheckYourAnswersBeforeSubmittingYourReturn,
      getChangeDoYouWantConfirmationByEmailThatThisReturnHasBeenSuccessfullySubmitted,
      postChangeDoYouWantConfirmationByEmailThatThisReturnHasBeenSuccessfullySubmitted("true"),
      getEnterYourEmailAddress,
      postEnterYourEmailAddress("test123@test.com"),
      getCheckYourAnswersBeforeSubmittingYourReturn,
      postCheckYourAnswersBeforeSubmittingYourReturn,
      postSubmissionSendPage
//      getPollingPage
    )
//    .withActions(pollUntilReady(postPollingPage).actionBuilders.reverse: _*)
//    .withRequests(getSuccessfulSubmissionPage)

  setup("nil-monthly-return", "NMRP")
    .withRequests(
      getFileYourNilReturnPage,
      postFileYourNilReturnPage,
      getConfirmNilReturnDatePage,
      postConfirmNilReturnDatePage,
      getDoYouWantToSubmitAnInactivityRequestPage,
      postDoYouWantToSubmitAnInactivityRequestPage("false"),
      getDoYouWantEmailConfirmation,
      postDoYouWantEmailConfirmation("true"),
      getConfirmEmailAddressPage,
      postConfirmEmailAddressPage("tester.test@test.com"),
      getDeclarationPage,
      postDeclarationPage,
      getMNRFCheckYourAnswersPage,
      getChangeDoYouWantToSubmitAnInactivityRequestPage,
      postChangeDoYouWantToSubmitAnInactivityRequestPage("true"),
      getChangeInactivityWarningPage,
      getMNRFCheckYourAnswersPage,
      getChangeEnterEmailAddressPage,
      postChangeEnterEmailAddressPage("Submissionsuccessful@test.com"),
      getMNRFCheckYourAnswersPage,
      postMNRFCheckYourAnswersPage,
      postSubmissionSendPage
//      getPollingPage
    )
//    .withActions(pollUntilReady(postPollingPage).actionBuilders.reverse: _*)
//    .withRequests(getSuccessfulSubmissionPage)

  setup("view-returns-history", "VRH").withRequests(
    getClickManageCISReturnLink,
    getManageYourCISReturnPage,
    getIncompleteReturnPage,
    getManageYourCISReturnPage,
    getTaxYearToViewPage,
    postTaxYearToViewPage("2024 to 2025"),
    getMonthlyReturnHistorySingleYear("2024"),
    getTaxYearToViewPage,
    postTaxYearToViewPage("all")
  )

  setup("amend-submitted-returns", "AmSR")
    .withRequests(
      getManageYourCISReturnPage,
      getWhichTaxYearToView,
      postWhichTaxYearToView("all"),
      getMonthlyReturnHistoryForAllTaxYears,
      getConfirmAmendmentRedirect("2025", "1"),
      getConfirmAmendmentPage,
      postConfirmAmendmentPage,
      getWhatDoYouWantToAmendNilReturn,
      postWhatDoYouWantToAmendNilReturn("addPaymentOrSubcontractorDetails"),
      getWhichSubcontractorDoYouWantToAdd,
      postWhichSubcontractorDoYouWantToAdd,
      getYouHaveAddedDetailsForTwoSubcontractors,
      getHowMuchDidYouPayToFirstSubcontractorInTotal,
      postHowMuchDidYouPayToFirstSubcontractorInTotal("1000"),
      getHowMuchDidFirstSubcontractorPayInMaterialCosts,
      postHowMuchDidFirstSubcontractorPayInMaterialCosts("200"),
      getHowMuchTaxInTotalDidYouDeductFromFirstSubcontractor,
      postHowMuchTaxInTotalDidYouDeductFromFirstSubcontractor("25"),
      getCheckYourAnswersForFirstSubcontractor,
      postCheckYourAnswersForFirstSubcontractor,
      getYouHaveAddedDetailsForTwoSubcontractors,
      getAreYouSureYouWantToRemoveFirstSubcontractor,
      postAreYouSureYouWantToRemoveFirstSubcontractor("true"),
      getYouHaveAddedDetailsForASingleSubcontractor,
      getHowMuchDidYouPayToSecondSubcontractorInTotal,
      postHowMuchDidYouPayToSecondSubcontractorInTotal("5000"),
      getHowMuchDidSecondSubcontractorPayInMaterialCosts,
      postHowMuchDidSecondSubcontractorPayInMaterialCosts("2000"),
      getHowMuchTaxInTotalDidYouDeductFromSecondSubcontractor,
      postHowMuchTaxInTotalDidYouDeductFromSecondSubcontractor("1000"),
      getCheckYourAnswersForSecondSubcontractor,
      postCheckYourAnswersForSecondSubcontractor,
      getYouHaveAddedDetailsForASingleSubcontractor,
      postYouHaveAddedDetailsForASingleSubcontractor("false"),
      getSummaryOfPaymentsMade,
      getDoYouConfirmTheInformationInThisReturnIsCorrect,
      postDoYouConfirmTheInformationInThisReturnIsCorrect("true"),
      getDeclarationOfEmploymentStatus,
      postDeclarationOfEmploymentStatus("true"),
      getDeclarationOfVerifiedStatus,
      postDeclarationOfVerifiedStatus("true"),
      getSubmitInactivityRequest,
      postSubmitInactivityRequest("false"),
      getDoYouWantConfirmationByEmailThatThisReturnHasBeenSuccessfullySubmitted,
      postDoYouWantConfirmationByEmailThatThisReturnHasBeenSuccessfullySubmitted("false"),
      getCheckYourAnswersBeforeSubmittingYourReturn
//      postCheckYourAnswersBeforeSubmittingYourReturn,
//      postSubmissionSendPage,
//      getPollingPage
    )
//    .withActions(pollUntilReady(postPollingPage).actionBuilders.reverse: _*)
    .withRequests(
//      getSuccessfulSubmissionPage,
//      returnToMonthlyReturnLandingPageRedirect,
      getManageYourCISReturnPage,
      getWhichTaxYearToView,
      postWhichTaxYearToView("all"),
      getMonthlyReturnHistoryForAllTaxYears,
      getConfirmAmendmentRedirect("2024", "6"),
      getConfirmAmendmentPage,
      postConfirmAmendmentPage,
      getWhatDoYouWantToAmendStandardReturn,
      postWhatDoYouWantToAmendStandardReturn("amendToNilReturn"),
      getWantToAmendStandardToNil,
      postWantToAmendStandardToNil("yes"),
      getSubmitInactivityRequest,
      postSubmitInactivityRequest("false"),
      getDoYouWantConfirmationByEmailThatThisReturnHasBeenSuccessfullySubmitted,
      postDoYouWantConfirmationByEmailThatThisReturnHasBeenSuccessfullySubmitted("false"),
      getDeclarationPage,
      postDeclarationPage,
      getCheckYourAnswersBeforeSubmittingYourReturn,
      postCheckYourAnswersBeforeSubmittingYourReturn,
      postSubmissionSendPage
//      getPollingPage
    )
//    .withActions(pollUntilReady(postPollingPage).actionBuilders.reverse: _*)
//    .withRequests(getSuccessfulSubmissionPage)

//  This scenario covers scenarios 1, 2, 6, 8 & 9 in the cis-ui-tests as the same pages are loaded ending at the Manage your CIS return subcontractor page.
  // Mechanics and database interaction are irrelevant when dealing with a stub.
  setup("successful-prepopulation", "SPR ").withRequests(
    getAuthPage,
    postManageAuthPage("Organisation", "EZ10400"),
    getSession,
    getManageFrontend,
    getSignIntoCISPage,
    getSignIntoCISRouting,
    getCisReturnDashboardPage,
    getClickSubcontractorsLink,
    getCheckSubcontractorRecordsPage("EZ10400"),
    postCheckSubcontractorRecordsPage("EZ10400"),
    getYourSubcontractors("EZ10400"),
    getStartPrepopulation("EZ10400"),
    getSuccessfulAutomaticSubcontractorUpdatePage,
    postSuccessfulAutomaticSubcontractorUpdatePage,
    getManageYourCISReturnSubcontractorPage("800")
//    continue journey to add subcontractor, verify subcontractor or subcontractor list
  )

  //  This scenario covers scenarios 3, 4, 5 & 7 in the cis-ui-tests as the same pages are loaded ending at the Add subcontractor page.
  //  Mechanics and database interaction are irrelevant when dealing with a stub.
  setup("unsuccessful-prepopulation", "UPR ").withRequests(
    getAuthPage,
    postManageAuthPage("Organisation", "EZ10450"),
    getSession,
    getManageFrontend,
    getSignIntoCISPage,
    getSignIntoCISRouting,
    getCisReturnDashboardPage,
    getClickSubcontractorsLink,
    getCheckSubcontractorRecordsPage("EZ10450"),
    postCheckSubcontractorRecordsPage("EZ10450"),
    getYourSubcontractors("EZ10450"),
    getStartPrepopulation("EZ10450"),
    getUnsuccessfulAutomaticSubcontractorUpdatePage,
    postUnsuccessfulAutomaticSubcontractorUpdatePage,
    getManageContractorDetailsRedirect,
    getAddContractorDetailsPage,
    postAddContractorDetailsPage
  )

  setup("add-individual-subcontractor", "AISP").withRequests(
    getClickSubcontractorsLink,
    getManageYourCISReturnSubcontractorPage("800"),
    getAddSubcontractor,
    getWhatTypeOfSubcontractorAreYouAdding,
    postWhatTypeOfSubcontractorAreYouAdding("soletrader"),
    getAddName,
    postAddName("tradingName"),
    getTradingName,
    postTradingName("Test Subcontractor Ltd"),
    getAddIndividualAddressPage,
    postAddIndividualAddressPage("true"),
    setIndividualAddressLookupNormalMode,
    getAddressLookupBegin,
    getAddressLookupCountryPicker,
    postAddressLookupCountryPicker("IE-Ireland"),
    getManuallyEnterAddressPage,
    postManuallyEnterAddressPage(
      "25 Oakley Road",
      "Flat 69",
      "",
      "City of Test",
      "SW22 42F",
      "IE"
    ),
    getReviewAddress,
    postReviewAddress,
    getReturnToIndividualNormalModeFrontendService,
    getAddIndividualContactDetailsPage,
    postAddIndividualContactDetailsPage("false"),
    getAddIndividualUtrPage,
    postAddIndividualUtrPage("true"),
    getIndividualUtrPage,
    postIndividualUtrPage("1234567895"),
    getAddIndividualNinoPage,
    postAddIndividualNinoPage("true"),
    getIndividualNinoPage,
    postIndividualNinoPage("AA123456C"),
    getAddIndividualWrnPage,
    postAddIndividualWrnPage("true"),
    getIndividualWrnPage,
    postIndividualWrnPage("12345678"),
    getIndividualCheckYourAnswersPage,
    getIndividualCheckYourAnswersPage,
    getChangeTradingNamePage,
    postChangeTradingNamePage("New Test Subcontractor Ltd"),
    getIndividualCheckYourAnswersPage,
    getChangeAddNamesPage,
    postChangeAddNamesPage("subcontractorName"),
    getChangeIndividualNamePage,
    postChangeIndividualNamePage("John", "Test", "Doe"),
    getIndividualCheckYourAnswersPage,
    getChangeIndividualNamePage,
    postChangeIndividualNamePage("Jane", "Tester", "Doe"),
    getIndividualCheckYourAnswersPage,
    setIndividualAddressLookupCheckMode,
    getAddressLookupBegin,
    getAddressLookupCountryPicker,
    postAddressLookupCountryPicker("GB-United_Kingdom"),
    getFindAddressWithPostcode,
    postFindAddressWithPostcode("AB21 3DE", "1243"),
    getManuallyEnterAddressPage,
    postManuallyEnterAddressPage(
      "123 Test Ave",
      "Flat 456",
      "",
      "Testing City",
      "AB21 3DE",
      "GB"
    ),
    getReviewAddress,
    postReviewAddress,
    getReturnToIndividualCheckModeFrontendService,
    getIndividualCheckYourAnswersPage,
    getChangeAddIndividualAddressPage,
    postChangeAddIndividualAddressPage("false"),
    getIndividualCheckYourAnswersPage,
    getChangeAddIndividualContactDetailsPage,
    postChangeAddIndividualContactDetailsPage("true"),
    getChangeIndividualContactMethodPage,
    postChangeIndividualContactMethodPage("email"),
    getChangeIndividualEmailAddressPage,
    postChangeIndividualEmailAddressPage("test@domain.co.uk"),
    getIndividualCheckYourAnswersPage,
    getChangeIndividualNinoPage,
    postChangeIndividualNinoPage("JJ123456A"),
    getIndividualCheckYourAnswersPage,
    getChangeAddIndividualNinoPage,
    postChangeAddIndividualNinoPage("false"),
    getIndividualCheckYourAnswersPage,
    getChangeIndividualUtrPage,
    postChangeIndividualUtrPage("7777777777"),
    getIndividualCheckYourAnswersPage,
    getChangeAddIndividualUtrPage,
    postChangeAddIndividualUtrPage("false"),
    getIndividualCheckYourAnswersPage,
    getChangeIndividualWrnPage,
    postChangeIndividualWrnPage("78789934"),
    getIndividualCheckYourAnswersPage,
    getChangeAddIndividualWrnPage,
    postChangeAddIndividualWrnPage("false"),
    getIndividualCheckYourAnswersPage,
    postIndividualCheckYourAnswersPage,
    getIndividualSubcontractorAddedPage
  )

  setup("add-partnership-subcontractor", "APSP").withRequests(
    getClickSubcontractorsLink,
    getManageYourCISReturnSubcontractorPage("800"),
    getAddSubcontractor,
    getWhatTypeOfSubcontractorAreYouAdding,
    postWhatTypeOfSubcontractorAreYouAdding("partnership"),
    getPartnershipNamePage,
    postPartnershipNamePage("CIS Test Partnership"),
    getAddPartnershipAddressPage,
    postAddPartnershipAddressPage("true"),
    setPartnershipAddressLookupNormalMode,
    getAddressLookupBegin,
    getAddressLookupCountryPicker,
    postAddressLookupCountryPicker("GB-United_Kingdom"),
    getFindAddressWithPostcode,
    postFindAddressWithPostcode("AB1 2CD", "123"),
    getCannotFindAddress,
    getManuallyEnterAddressPage,
    postManuallyEnterAddressPage(
      "123 Test Drive",
      "Flat 456",
      "",
      "Manchester city",
      "AB1 2CD",
      "GB"
    ),
    getReviewAddress,
    postReviewAddress,
    getReturnToPartnershipNormalModeFrontendService,
    getAddPartnershipContactDetailsPage,
    postAddPartnershipContactDetailsPage(true),
    getPartnershipContactMethodPage,
    postPartnershipContactMethodPage("email"),
    getPartnershipEmailAddressPage,
    postPartnershipEmailAddressPage("john.doe@domainurl.com"),
    getAddPartnershipUTRPage,
    postAddPartnershipUTRPage("true"),
    getPartnershipUTRPage,
    postPartnershipUTRPage("1234567895"),
    getNominatedPartnerName,
    postNominatedPartnerName("Test Nominated Partner"),
    getAddNominatedPartnerUTRPage,
    postAddNominatedPartnerUTRPage("true"),
    getNominatedPartnerUTRPage,
    postNominatedPartnerUTRPage("9999999999"),
    getAddNominatedPartnerNinoPage,
    postAddNominatedPartnerNinoPage("true"),
    getNominatedPartnerNinoPage,
    postNominatedPartnerNinoPage("AA123456C"),
    getAddNominatedPartnerCrnPage,
    postAddNominatedPartnerCrnPage("true"),
    getNominatedPartnerCrnPage,
    postNominatedPartnerCrnPage("12345678"),
    getAddPartnershipWrnPage,
    postAddPartnershipWrnPage("true"),
    getPartnershipWrnPage,
    postPartnershipWrnPage("ref12345"),
    getPartnershipCheckYourAnswersPage,
    postPartnershipCheckYourAnswersPage,
    getChangePartnershipNamePage,
    postChangePartnershipNamePage("CIS Test Partnership Change"),
    getPartnershipCheckYourAnswersPage,
    setPartnershipAddressLookupCheckMode,
    setPartnershipAddressLookupCheckMode,
    getAddressLookupBegin,
    getAddressLookupCountryPicker,
    postAddressLookupCountryPicker("IE-Ireland"),
    getManuallyEnterAddressPage,
    postManuallyEnterAddressPage(
      "123 Test Drive Change",
      "Flat 456 Change",
      "Dublin city Change",
      "Dublin Change",
      "AB1 2CE",
      "IE"
    ),
    getReviewAddress,
    postReviewAddress,
    getReturnToPartnershipCheckModeFrontendService,
    getPartnershipCheckYourAnswersPage,
    getChangePartnershipEmailAddressPage,
    postChangePartnershipEmailAddressPage("john.doe.update@domainurl.com"),
    getPartnershipCheckYourAnswersPage,
    getChangePartnershipContactMethodPage,
    postChangePartnershipContactMethodPage("phone", "mobile"),
    getChangePartnershipPhoneNumberPage,
    postChangePartnershipPhoneNumberPage("01415008500"),
    getChangePartnershipMobileNumberPage,
    postChangePartnershipMobileNumberPage("+447543445421"),
    getPartnershipCheckYourAnswersPage,
    getPartnershipCheckYourAnswersPage,
    getChangePartnershipUTRPage,
    postChangePartnershipUTRPage("1234567896"),
    getPartnershipCheckYourAnswersPage,
    getChangeNominatedPartnerName,
    postChangeNominatedPartnerName("Test Nominated Partner Change"),
    getPartnershipCheckYourAnswersPage,
    getChangeNominatedPartnerUTRPage,
    postChangeNominatedPartnerUTRPage("9999999999"),
    getPartnershipCheckYourAnswersPage,
    getChangeNominatedPartnerNinoPage,
    postChangeNominatedPartnerNinoPage("AB123456D"),
    getPartnershipCheckYourAnswersPage,
    getChangeNominatedPartnerCrnPage,
    postChangeNominatedPartnerCrnPage("12345670"),
    getPartnershipCheckYourAnswersPage,
    getChangePartnershipWrnPage,
    postChangePartnershipWrnPage("ref54321"),
    getPartnershipCheckYourAnswersPage,
    getChangeAddPartnershipUTRPage,
    postChangeAddPartnershipUTRPage("false"),
    getPartnershipCheckYourAnswersPage,
    getChangeAddNominatedPartnerUTRPage,
    postChangeAddNominatedPartnerUTRPage("false"),
    getPartnershipCheckYourAnswersPage,
    getChangeAddNominatedPartnerNinoPage,
    postChangeAddNominatedPartnerNinoPage("false"),
    getPartnershipCheckYourAnswersPage,
    getChangeAddNominatedPartnerCrnPage,
    postChangeAddNominatedPartnerCrnPage("false"),
    getPartnershipCheckYourAnswersPage,
    getChangeAddPartnershipWrnPage,
    postChangeAddPartnershipWrnPage("false"),
    getPartnershipCheckYourAnswersPage,
    postPartnershipCheckYourAnswersPage,
    getPartnershipSubcontractorAddedPage
  )

  setup("add-company-subcontractor", "ACSP").withRequests(
    getClickSubcontractorsLink,
    getManageYourCISReturnSubcontractorPage("800"),
    getAddSubcontractor,
    getWhatTypeOfSubcontractorAreYouAdding,
    postWhatTypeOfSubcontractorAreYouAdding("company"),
    getCompanyNamePage,
    postCompanyNamePage("CIS Test Company"),
    getAddCompanyAddressPage,
    postAddCompanyAddressPage("false"),
    getCompanyContactDetailsPage,
    postCompanyContactDetailsPage("false"),
    getAddCompanyUTRPage,
    postAddCompanyUTRPage("false"),
    getAddCompanyCrnPage,
    postAddCompanyCrnPage("false"),
    getAddCompanyWrnPage,
    postAddCompanyWrnPage("false"),
    getCompanyCheckYourAnswersPage,
    getChangeCompanyNamePage,
    postChangeCompanyNamePage("New CIS Test Company"),
    getCompanyCheckYourAnswersPage,
    getChangeAddCompanyAddressPage,
    postChangeAddCompanyAddressPage("true"),
    setCompanyAddressLookupCheckMode,
    getAddressLookupBegin,
    getAddressLookupCountryPicker,
    postAddressLookupCountryPicker("GB-United_Kingdom"),
    getFindAddressWithPostcode,
    postFindAddressWithPostcode("SW1 1SW", "5"),
    getCannotFindAddress,
    getManuallyEnterAddressPage,
    postManuallyEnterAddressPage(
      "125 Hill Street",
      "Flat 96",
      "Floor 7",
      "Test City",
      "SW1 1SW",
      "GB"
    ),
    getReviewAddress,
    postReviewAddress,
    getReturnToCompanyCheckModeFrontendService,
    getCompanyCheckYourAnswersPage,
    getChangeAddCompanyContactDetailsPage,
    postChangeAddCompanyContactDetailsPage("true"),
    getChangeCompanyContactMethodPage,
    postChangeCompanyContactMethodPage("mobile"),
    getChangeCompanyMobileNumberPage,
    postChangeCompanyMobileNumberPage("0987654321"),
    getCompanyCheckYourAnswersPage,
    getChangeAddCompanyUTRPage,
    postChangeAddCompanyUTRPage("true"),
    getChangeCompanyUTRPage,
    postChangeCompanyUTRPage("1234567895"),
    getCompanyCheckYourAnswersPage,
    getChangeAddCompanyCrnPage,
    postChangeAddCompanyCrnPage("true"),
    getChangeCompanyCrnPage,
    postChangeCompanyCrnPage("10000008"),
    getCompanyCheckYourAnswersPage,
    getChangeAddCompanyWrnPage,
    postChangeAddCompanyWrnPage("true"),
    getChangeCompanyWrnPage,
    postChangeCompanyWrnPage("123456780"),
    getCompanyCheckYourAnswersPage,
    postCompanyCheckYourAnswersPage,
    getCompanySubcontractorAddedPage
  )

  setup("add-trust-subcontractor", "ATSP").withRequests(
    getClickSubcontractorsLink,
    getManageYourCISReturnSubcontractorPage("800"),
    getAddSubcontractor,
    getWhatTypeOfSubcontractorAreYouAdding,
    postWhatTypeOfSubcontractorAreYouAdding("trust"),
    getTrustNamePage,
    postTrustNamePage("CIS Test Trust"),
    getAddTrustAddressPage,
    postAddTrustAddressPage("false"),
    getTrustContactDetailsPage,
    postTrustContactDetailsPage("false"),
    getAddTrustUTRPage,
    postAddTrustUTRPage("false"),
    getAddTrustWrnPage,
    postAddTrustWrnPage("false"),
    getTrustCheckYourAnswersPage,
    getChangeTrustNamePage,
    postChangeTrustNamePage("CIS Test Trust Change"),
    getTrustCheckYourAnswersPage,
    getChangeAddTrustAddressPage,
    postChangeAddTrustAddressPage("true"),
    setTrustAddressLookupCheckMode,
    getAddressLookupBegin,
    getAddressLookupCountryPicker,
    postAddressLookupCountryPicker("IE-Ireland"),
    getManuallyEnterAddressPage,
    postManuallyEnterAddressPage(
      "123 Test Drive Change",
      "Flat 456 Change",
      "Dublin city Change",
      "Dublin Change",
      "AB1 2CE",
      "IE"
    ),
    getReviewAddress,
    postReviewAddress,
    getReturnToTrustCheckModeFrontendService,
    getTrustCheckYourAnswersPage,
    getChangeAddTrustContactDetailsPage,
    postChangeAddTrustContactDetailsPage("true"),
    getChangeTrustContactMethodPage,
    postChangeTrustContactMethodPage("email"),
    getChangeTrustEmailAddressPage,
    postChangeTrustEmailAddressPage("john.doe.update@hmrc.co.uk"),
    getTrustCheckYourAnswersPage,
    getChangeAddTrustWrnPage,
    postChangeAddTrustWrnPage("true"),
    getChangeTrustWrnPage,
    postChangeTrustWrnPage("ref54321"),
    getTrustCheckYourAnswersPage,
    getChangeAddTrustUTRPage,
    postChangeAddTrustUTRPage("true"),
    getChangeTrustUTRPage,
    postChangeTrustUTRPage("1234567895"),
    getTrustCheckYourAnswersPage,
    postTrustCheckYourAnswersPage,
    getTrustSubcontractorAddedPage
  )

  setup("amend-individual-subcontractor", "AmIS").withRequests(
    getClickSubcontractorsLink,
    getManageYourCISReturnSubcontractorPage("800"),
    getRetrieveSubcontractorList,
    getYourSubcontractorListPage,
    getSubcontractorInformationRedirect("2"),
    getSubcontractorInformationPage("2"),
    postSubcontractorInformationPage("2"),
    getYourSubcontractorListPage,
    getSubcontractorInformationRedirect("2"),
    getSubcontractorInformationPage("2"),
    getCancelChanges,
    getYourSubcontractorListPage,
    getSubcontractorInformationRedirect("2"),
    getSubcontractorInformationPage("2"),
    getAmendNameOptions,
    postAmendNameOptions(0, "subcontractorName"),
    getAmendSubcontractorName,
    postAmendSubcontractorName("John", "Middle", "Doe"),
    getSubcontractorInformationPageNoSubbieRef,
    postAmendNameOptions(1, "tradingName"),
    postAmendTradingName("Individual Trading Ltd"),
    getSubcontractorInformationPageNoSubbieRef,
    getRemoveAddress,
    postRemoveAddress("false"),
    getSubcontractorInformationPageNoSubbieRef,
    getAddressChangeRedirect,
    getIndividualAddressLookupAmendMode,
    getAddressLookupBegin,
    getAddressLookupCountryPicker,
    postAddressLookupCountryPicker("GB-United_Kingdom"),
    getFindAddressWithPostcode,
    postFindAddressWithPostcode("SW1 1SW", "55"),
    getCannotFindAddress,
    getManuallyEnterAddressPage,
    postManuallyEnterAddressPage(
      "125 Hill Street",
      "Flat 96",
      "Floor 7",
      "Test City",
      "SW1 1SW",
      "GB"
    ),
    getReviewAddress,
    postReviewAddress,
    getReturnToIndividualAmendModeFrontendService,
    getSubcontractorInformationPageNoSubbieRef,
    getRemoveContactDetails,
    postRemoveContactDetails("true"),
    getSubcontractorInformationPageNoSubbieRef,
    getAddContactDetails,
    postAddContactDetails("true"),
    getSelectContactDetailsToAdd,
    postSelectContactDetailsToAdd,
    getEnterEmailAddress,
    postEnterEmailAddress("individual_email123@gov.uk"),
    getEnterPhoneNumber,
    postEnterPhoneNumber("1234567890"),
    getEnterMobileNumber,
    postEnterMobileNumber("09876543214"),
    getSubcontractorInformationPageNoSubbieRef,
    getEnterNINumber,
    postEnterNINumber("PJ123456C"),
    getSubcontractorInformationPageNoSubbieRef,
    getEnterWorksRefNumber,
    postEnterWorksRefNumber("INDIVIDUAL-REF-123"),
    postIndividualSubcontractorInformationPage,
    getIndividualSubcontractorUpdated
  )

  setup("amend-company-subcontractor", "AmCS").withRequests(
    getClickSubcontractorsLink,
    getManageYourCISReturnSubcontractorPage("800"),
    getRetrieveSubcontractorList,
    getYourSubcontractorListPage,
    getSubcontractorInformationRedirect("4"),
    getCompanySubcontractorInformationPage("4"),
    postCompanySubcontractorInformationPage,
    getYourSubcontractorListPage,
    getSubcontractorInformationRedirect("4"),
    getCompanySubcontractorInformationPage("4"),
    getCancelChanges,
    getYourSubcontractorListPage,
    getSubcontractorInformationRedirect("4"),
    getCompanySubcontractorInformationPage("4"),
    getAmendCompanyName,
    postAmendCompanyName("New organisation Company Name"),
    getCompanySubcontractorInformationPageNoSubbieRef,
    getCompanyAddressChangeRedirect,
    getCompanyAddressLookupAmendMode,
    getAddressLookupBegin,
    getAddressLookupCountryPicker,
    postAddressLookupCountryPicker("GB-United_Kingdom"),
    getFindAddressWithPostcode,
    postFindAddressWithPostcode("SW1 1SW", "123"),
    getCannotFindAddress,
    getManuallyEnterAddressPage,
    postManuallyEnterAddressPage(
      "125 Hill Street",
      "Flat 96",
      "Floor 7",
      "Test City",
      "SW1 1SW",
      "GB"
    ),
    getReviewAddress,
    postReviewAddress,
    getReturnToCompanyAmendModeFrontendService,
    getCompanySubcontractorInformationPageNoSubbieRef,
    getAmendCompanyEmailAddress,
    postAmendCompanyEmailAddress("cis_company_email@domain.com"),
    getCompanySubcontractorInformationPageNoSubbieRef,
    getEnterCompanyUTR,
    postEnterCompanyUTR("1111122222"),
    getEnterCompanyRegNumber,
    postEnterCompanyRegNumber("PE000000"),
    getEnterCompanyWorksRefNumber,
    postEnterCompanyWorksRefNumber("COMP-789"),
    postCompanySubcontractorInformationPage,
    getCompanySubcontractorUpdated
  )

  setup("amend-partnership-subcontractor", "AmPS").withRequests(
    getClickSubcontractorsLink,
    getManageYourCISReturnSubcontractorPage("800"),
    getRetrieveSubcontractorList,
    getYourSubcontractorListPage,
    getYourSubcontractorListPage2,
    getSubcontractorInformationRedirect("6"),
    getPartnershipSubcontractorInformationPage("6"),
    getRemovePartnershipAddress,
    postRemovePartnershipAddress("true"),
    getPartnershipSubcontractorInformationPageNoSubbieRef,
    getRemovePartnershipContactDetails,
    postRemovePartnershipContactDetails("true"),
    getPartnershipSubcontractorInformationPageNoSubbieRef,
    getRemovePartnershipUTR,
    postRemovePartnershipUTR("true"),
    getPartnershipSubcontractorInformationPageNoSubbieRef,
    getRemoveNominatedPartnerUTR,
    postRemoveNominatedPartnerUTR("true"),
    getPartnershipSubcontractorInformationPageNoSubbieRef,
    getRemoveNominatedPartnerNino,
    postRemoveNominatedPartnerNINO("true"),
    getPartnershipSubcontractorInformationPageNoSubbieRef,
    getRemoveNominatedPartnerCRN,
    postRemoveNominatedPartnerCRN("true"),
    getPartnershipSubcontractorInformationPageNoSubbieRef,
    getRemovePartnershipWRN,
    postRemovePartnershipWRN("true"),
    getPartnershipSubcontractorInformationPageNoSubbieRef,
    getAmendPartnershipName,
    postAmendPartnershipName("New Org partnership Name"),
    getPartnershipSubcontractorInformationPageNoSubbieRef,
    getAddPartnershipAddress,
    postAddPartnershipAddress("true"),
    getPartnershipAddressChangeRedirect,
    getPartnershipAddressLookupAmendMode,
    getAddressLookupBegin,
    getAddressLookupCountryPicker,
    postAddressLookupCountryPicker("GB-United_Kingdom"),
    getFindAddressWithPostcode,
    postFindAddressWithPostcode("SW1 1SW", "123"),
    getCannotFindAddress,
    getManuallyEnterAddressPage,
    postManuallyEnterAddressPage(
      "125 Hill Street",
      "Flat 96",
      "Floor 7",
      "Test City",
      "SW1 1SW",
      "GB"
    ),
    getReviewAddress,
    postReviewAddress,
    getReturnToPartnershipAmendModeFrontendService,
    getPartnershipSubcontractorInformationPageNoSubbieRef,
    getAddPartnershipContactDetails,
    postAddPartnershipContactDetails("true"),
    getSelectContactDetailsToAddForPartnership,
    postSelectContactDetailsToAddForPartnership,
    getEnterPartnershipEmailAddress,
    postEnterPartnershipEmailAddress("testemail@test.com"),
    getEnterPartnershipPhoneNumber,
    postEnterPartnershipPhoneNumber("01910000000"),
    getEnterPartnershipMobileNumber,
    postEnterPartnershipMobileNumber("0733333333333"),
    getPartnershipSubcontractorInformationPageNoSubbieRef,
    getAddPartnershipUTR,
    postAddPartnershipUTR("true"),
    getEnterPartnershipUTR,
    postEnterPartnershipUTR("1111122222"),
    getPartnershipSubcontractorInformationPageNoSubbieRef,
    getAmendNominatedPartnerName,
    postAmendNominatedPartnerName("CIS Nominated Test Partner"),
    getPartnershipSubcontractorInformationPageNoSubbieRef,
    getAddNominatedPartnerUTR,
    postAddNominatedPartnerUTR("true"),
    getEnterNominatedPartnershipUTR,
    postEnterNominatedPartnershipUTR("5555555555"),
    getPartnershipSubcontractorInformationPageNoSubbieRef,
    getAddNominatedPartnerNino,
    postAddNominatedPartnerNINO("true"),
    getEnterNominatedPartnerNINO,
    postEnterNominatedPartnerNINO("ST456345D"),
    getPartnershipSubcontractorInformationPageNoSubbieRef,
    getAddNominatedPartnerCRN,
    postAddNominatedPartnerCRN("true"),
    getEnterNominatedPartnerCRN,
    postEnterNominatedPartnerCRN("TP712345"),
    getPartnershipSubcontractorInformationPageNoSubbieRef,
    getAddPartnershipWRN,
    postAddPartnershipWRN("true"),
    getEnterPartnershipWorksRefNumber,
    postEnterPartnershipWorksRefNumber("PART-REF-789"),
    postPartnershipSubcontractorInformationPage,
    getPartnershipSubcontractorUpdated
  )

  setup("amend-trust-subcontractor", "AmTS").withRequests(
    getClickSubcontractorsLink,
    getManageYourCISReturnSubcontractorPage("800"),
    getRetrieveSubcontractorList,
    getYourSubcontractorListPage,
    getYourSubcontractorListPage2,
    getSubcontractorInformationRedirect("8"),
    getTrustSubcontractorInformationPage("8"),
    getAmendTrustName,
    postAmendTrustName("Unverified CIS Trust"),
    getTrustSubcontractorInformationPageNoSubbieRef,
    getTrustAddressChangeRedirect,
    getTrustAddressLookupAmendMode,
    getAddressLookupBegin,
    getAddressLookupCountryPicker,
    postAddressLookupCountryPicker("GB-United_Kingdom"),
    getFindAddressWithPostcode,
    postFindAddressWithPostcode("SW1 1SW", "123"),
    getCannotFindAddress,
    getManuallyEnterAddressPage,
    postManuallyEnterAddressPage(
      "125 Hill Street",
      "Flat 96",
      "Floor 7",
      "Test City",
      "SW1 1SW",
      "GB"
    ),
    getReviewAddress,
    postReviewAddress,
    getReturnToTrustAmendModeFrontendService,
    getTrustSubcontractorInformationPageNoSubbieRef,
    getSelectContactDetailsToAddForTrust,
    postSelectContactDetailsToAddForTrust,
    getTrustSubcontractorInformationPageNoSubbieRef,
    getEnterTrustPhoneNumber,
    postEnterTrustPhoneNumber("0987654321"),
    getTrustSubcontractorInformationPageNoSubbieRef,
    getEnterTrustUTR,
    postEnterTrustUTR("7734321272"),
    getTrustSubcontractorInformationPageNoSubbieRef,
    getEnterTrustWorksRefNumber,
    postEnterTrustWorksRefNumber("organisation-REF-123"),
    getTrustSubcontractorInformationPageNoSubbieRef,
    postTrustSubcontractorInformationPage,
    getTrustSubcontractorUpdated
  )

  setup("delete-subcontractor", "DSP").withRequests(
    getClickSubcontractorsLink,
    getManageYourCISReturnSubcontractorPage("800"),
    getRetrieveSubcontractorList,
    getYourSubcontractorListPage,
    getYourSubcontractorListPage2,
    getDeleteStatus("7"),
    getCannotDeletePage,
    getYourSubcontractorListPage,
    getDeleteStatus("2"),
    getDeleteSubcontractorOption,
    postDeleteSubcontractorOption("true"),
    getSubcontractorDeleted
  )

  setup("verify-subcontractor", "VSP")
    .withRequests(
      getVerifySubcontractor,
      getVerifyWhichSubcontractorPage,
      postVerifyWhichSubcontractorPage(),
      getReverifyExistingSubcontractorPage,
      postReverifyExistingSubcontractorPage(),
      getReverifySelectSubcontractorPage,
      postReverifySelectSubcontractorPage(),
      getCurrentSubcontractorsToVerify,
      getModifyVerificationBatch,
      getCheckVerificationBatchReadiness,
      getVerifyEmailConfirmationPage,
      postVerifyEmailConfirmationPage("differentEmail"),
      getVerifyEnterEmailConfirmationPage,
      postVerifyEnterEmailConfirmationPage("test@test.com"),
      getVerificationCheckYourAnswersPage,
      postVerificationCheckYourAnswersPage,
      getSubmittingVerificationRequestPage
//      getVerificationPollingPage
    )
//    .withActions(pollUntilReady(postVerificationPollingPage).actionBuilders.reverse: _*)
//    .withRequests(getVerificationRequestSubmittedPage)

  setup("review-unmatched-subcontractors", "RUSP").withRequests(
    getAuthPage,
    postManageAuthPage("Organisation", "EZ00250"),
    getSession,
    getManageFrontend,
    getSignIntoCISPage,
    getSignIntoCISRouting,
    getCisReturnDashboardPage,
    getClickSubcontractorsLink,
    getManageYourCISReturnSubcontractorPage("250"),
    getVerifySubcontractor,
    getUnmatchedSubcontractorExist,
    getCheckResultsRedirect,
    getVerificationResults,
    getUnmatchedSubcontractorsRedirect,
    getReviewUnmatchedSubcontractorsPage,
    getUnmatchedSubcontractorInfoRedirect("19"),
    getUnmatchedSubcontractorInfoReadOnly,
    getReviewUnmatchedSubcontractorsPage,
    getEditUnmatchedSubcontractorInfoRedirect("19"),
    getSubcontractorInformationPage("19"),
    getCancelChanges,
    getUnmatchedSubcontractorsRedirect,
    getReviewUnmatchedSubcontractorsPage,
    getProceedUnmatchedOptionPage,
    postProceedUnmatchedOptionPage("true"),
    getReviewUnmatchedSubcontractorsPage,
    getRemoveUnmatchedOptionPage,
    postRemoveUnmatchedOptionPage("true"),
    getReviewUnmatchedSubcontractorsPage,
    getVerificationResults
  )

  setup("review-insufficient-subcontractors", "RISP").withRequests(
    getAuthPage,
    postManageAuthPage("Organisation", "EZ00275"),
    getSession,
    getManageFrontend,
    getSignIntoCISPage,
    getSignIntoCISRouting,
    getCisReturnDashboardPage,
    getClickSubcontractorsLink,
    getManageYourCISReturnSubcontractorPage("275"),
    getVerifySubcontractor,
    getVerifyWhichSubcontractorPage,
    postVerifyWhichInsufficientSubcontractor,
    getVerifyWhichSubcontractorPage2,
    getReverifyExistingSubcontractorPage,
    postReverifyExistingSubcontractorPage(),
    getReverifySelectSubcontractorPage,
    postReverifySelectSubcontractorPage(),
    getCurrentSubcontractorsToVerify,
    getCheckVerificationBatchReadiness,
    getSubcontractorHaveMissingInformation,
    getInsufficientSubcontractorInfoRedirect("10"),
    getInsufficientSubcontractorInfoReadOnly,
    getSubcontractorHaveMissingInformation,
    getEditInsufficientSubcontractorInfoRedirect("10"),
    getSubcontractorInformationPage("10"),
    getCancelChanges,
    getSubcontractorHaveMissingInformation,
    getInsufficientOptionPage,
    postProceedInsufficientOptionPage("true"),
    getSubcontractorHaveMissingInformation,
    getRemoveInsufficientOptionPage,
    postRemoveInsufficientOptionPage("true"),
    getSubcontractorHaveMissingInformation
  )

  setup("view-verification-history", "VVHP").withRequests(
    getAuthPage,
    postManageAuthPage("Organisation", "EZ00150"),
    getSession,
    getManageFrontend,
    getSignIntoCISPage,
    getSignIntoCISRouting,
    getCisReturnDashboardPage,
    getClickSubcontractorsLink,
    getManageYourCISReturnSubcontractorPage("150"),
    getSelectTaxYear,
    postSelectTaxYear("all"),
    getAllTaxYear,
    getViewVerificationRequest("199"),
    getManageYourCISReturnSubcontractorPage("150"),
    getSelectTaxYear,
    postSelectTaxYear("all"),
    getViewSubmissionReceipt("399")
  )
  runSimulation()
}
