/*
 * Copyright 2023 HM Revenue & Customs
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package uk.gov.hmrc.perftests.cis.simulations

import io.gatling.core.scenario.Simulation
import uk.gov.hmrc.performance.simulation.PerformanceTestRunner
import uk.gov.hmrc.perftests.cis.requests.AuthRequests._
import uk.gov.hmrc.perftests.cis.requests.LandingPagesRequests._
import uk.gov.hmrc.perftests.cis.requests.NilMonthlyReturnRequests._
import uk.gov.hmrc.perftests.cis.requests.PrepopulationRequests._
import uk.gov.hmrc.perftests.cis.requests.VerifySubcontractorRequests._
import uk.gov.hmrc.perftests.cis.requests.StandardMonthlyReturnRequests._
import uk.gov.hmrc.perftests.cis.requests.AddIndividualSubcontractorRequests._
import uk.gov.hmrc.perftests.cis.requests.AddPartnershipSubcontractorRequests._
import uk.gov.hmrc.perftests.cis.requests.AddCompanySubcontractorRequests._
import uk.gov.hmrc.perftests.cis.requests.AddTrustSubcontractorRequests._

class CisSimulation extends Simulation with PerformanceTestRunner {

  setup("org-landing-pages", "OLP ").withRequests(
    getAuthPage,
    postManageAuthPage("Organisation", "EZ10800"),
    getSession,
    getManageFrontend,
    getSignIntoCISPage,
    getSignIntoCISRouting,
    getCisReturnDashboardPage
  )

  setup("agent-landing-pages", "ALP ").withRequests(
    getAuthPage,
    postManageAuthPage("Agent", "123456"),
    getSession,
    getManageFrontend,
    getSignIntoCISPage,
    getSignIntoCISRouting,
    getRetrieveClientList,
    getStartRetrieveClientList,
    getFileMonthlyCISReturnsUnfilteredListPage,
    postFileMonthlyCISReturnsSearchPage("ER", "EZ10800"),
    getClientFilteredViewFileMonthlyCISReturnPage,
    getClientCisReturnDashboardPage,
    getRedirectManageCISReturnPage,
    getManageYourCISReturnPage
  )

//  setup("standard-monthly-return", "SMRP").withRequests(
//    getFileYourMonthlyCISReturn,
//    getWhichTaxMonthAndYearAreYouFilingAReturnFor,
//    postWhichTaxMonthAndYearAreYouFilingAReturnFor,
//    getSelectSubcontractors,
//    getSelectAllSelectSubcontractors,
//    getDeselectAllSelectSubcontractors,
//    postSelectSubcontractors("31001", "31002"),
//    getYouHaveUnverifiedSubcontractors,
//    postYouHaveUnverifiedSubcontractors("false"),
//    getHowMuchDidYouPayToFirstSubcontractorInTotal,
//    postHowMuchDidYouPayToFirstSubcontractorInTotal("1000"),
//    getHowMuchDidFirstSubcontractorPayInMaterialCosts,
//    postHowMuchDidFirstSubcontractorPayInMaterialCosts("200"),
//    getHowMuchTaxInTotalDidYouDeductFromFirstSubcontractor,
//    postHowMuchTaxInTotalDidYouDeductFromFirstSubcontractor("25"),
//    getCheckYourAnswersForFirstSubcontractor,
//    getChangeHowMuchDidYouPayToFirstSubcontractorInTotal,
//    postChangeHowMuchDidYouPayToFirstSubcontractorInTotal("2000"),
//    getCheckYourAnswersForFirstSubcontractor,
//    getChangeHowMuchDidFirstSubcontractorPayInMaterialCosts,
//    postChangeHowMuchDidFirstSubcontractorPayInMaterialCosts("500"),
//    getCheckYourAnswersForFirstSubcontractor,
//    getChangeHowMuchTaxInTotalDidYouDeductFromFirstSubcontractor,
//    postChangeHowMuchTaxInTotalDidYouDeductFromFirstSubcontractor("125"),
//    getCheckYourAnswersForFirstSubcontractor,
//    postCheckYourAnswersForFirstSubcontractor,
//    getYouHaveAddedDetailsForASingleSubcontractor,
//    getChangeFirstSubcontractorsDetails,
//    getChangeHowMuchDidYouPayToFirstSubcontractorInTotalDetails,
//    postChangeHowMuchDidYouPayToFirstSubcontractorInTotalDetails("5000"),
//    getChangeFirstSubcontractorsDetails,
//    getChangeHowMuchDidFirstSubcontractorPayInMaterialCostsDetails,
//    postChangeHowMuchDidFirstSubcontractorPayInMaterialCostsDetails("1000"),
//    getChangeFirstSubcontractorsDetails,
//    getChangeHowMuchTaxInTotalDidYouDeductFromFirstSubcontractorDetails,
//    postChangeHowMuchTaxInTotalDidYouDeductFromFirstSubcontractorDetails("250"),
//    getChangeFirstSubcontractorsDetails,
//    postChangeFirstSubcontractorsDetails,
//    getYouHaveAddedDetailsForASingleSubcontractor,
//    postYouHaveAddedDetailsForASingleSubcontractor("false"),
//    getWhichSubcontractorDoYouNeedToAddPaymentDetailsFor,
//    postWhichSubcontractorDoYouNeedToAddPaymentDetailsFor("2"),
//    getHowMuchDidYouPayToSecondSubcontractorInTotal,
//    postHowMuchDidYouPayToSecondSubcontractorInTotal("5000"),
//    getHowMuchDidSecondSubcontractorPayInMaterialCosts,
//    postHowMuchDidSecondSubcontractorPayInMaterialCosts("2000"),
//    getHowMuchTaxInTotalDidYouDeductFromSecondSubcontractor,
//    postHowMuchTaxInTotalDidYouDeductFromSecondSubcontractor("1000"),
//    getCheckYourAnswersForSecondSubcontractor,
//    postCheckYourAnswersForSecondSubcontractor,
//    getYouHaveAddedDetailsFor2Subcontractors,
//    getAreYouSureYouWantToRemoveFirstSubcontractor,
//    postAreYouSureYouWantToRemoveFirstSubcontractor("true"),
//    getYouHaveAddedDetailsForASingleSubcontractor,
//    postYouHaveAddedDetailsForASingleSubcontractor("true"),
//    getSummaryOfPaymentsMade,
//    getDoYouConfirmTheInformationInThisReturnIsCorrect,
//    postDoYouConfirmTheInformationInThisReturnIsCorrect("true"),
//    getDeclarationOfEmploymentStatus,
//    postDeclarationOfEmploymentStatus("false"),
//    getDeclarationOfVerifiedStatus,
//    postDeclarationOfVerifiedStatus("false"),
//    getSubmitInactivityRequest,
//    postSubmitInactivityRequest("false"),
//    getDoYouWantConfirmationByEmailThatThisReturnHasBeenSuccessfullySubmitted,
//    postDoYouWantConfirmationByEmailThatThisReturnHasBeenSuccessfullySubmitted("false"),
//    getCheckYourAnswersBeforeSubmittingYourReturn,
//    getChangeDeclarationOfEmploymentStatus,
//    postChangeDeclarationOfEmploymentStatus("true"),
//    getCheckYourAnswersBeforeSubmittingYourReturn,
//    getChangeDeclarationOfVerifiedStatus,
//    postChangeDeclarationOfVerifiedStatus("true"),
//    getCheckYourAnswersBeforeSubmittingYourReturn,
//    getChangeSubmitInactivityRequest,
//    postChangeSubmitInactivityRequest("true"),
//    getInactivityRequest,
//    getCheckYourAnswersBeforeSubmittingYourReturn,
//    getChangeDoYouWantConfirmationByEmailThatThisReturnHasBeenSuccessfullySubmitted,
//    postChangeDoYouWantConfirmationByEmailThatThisReturnHasBeenSuccessfullySubmitted("true"),
//    getEnterYourEmailAddress,
//    postEnterYourEmailAddress("test123@test.com"),
//    getCheckYourAnswersBeforeSubmittingYourReturn,
//    postCheckYourAnswersBeforeSubmittingYourReturn,
//    postSubmissionSendPage,
//    getPollingPage,
//    getPollingPage,
//    // postPollingPage,   analysis for polling issue is being looked into
//    getSuccessfulSubmissionPage
//  )

//  setup("nil-monthly-return", "NMRP").withRequests(
//    getFileYourNilReturnPage,
//    getConfirmNilReturnPage,
//    postConfirmNilReturnPage,
//    getDoYouWantToSubmitAnInactivityRequestPage,
//    postDoYouWantToSubmitAnInactivityRequestPage("false"),
//    getDoYouWantEmailConfirmation,
//    postDoYouWantEmailConfirmation("true"),
//    getConfirmEmailAddressPage,
//    postConfirmEmailAddressPage("tester.test@test.com"),
//    getDeclarationPage,
//    postDeclarationPage,
//    getMNRFCheckYourAnswersPage,
//    getChangeDoYouWantToSubmitAnInactivityRequestPage,
//    postChangeDoYouWantToSubmitAnInactivityRequestPage("true"),
//    getChangeInactivityWarningPage,
//    getMNRFCheckYourAnswersPage,
//    getChangeEnterEmailAddressPage,
//    postChangeEnterEmailAddressPage("Submissionsuccessful@test.com"),
//    getMNRFCheckYourAnswersPage,
//    postMNRFCheckYourAnswersPage,
//    postSubmissionSendPage,
//    getPollingPage,
//    getPollingPage,
//    // postPollingPage,   analysis for polling issue is being looked into
//    getSuccessfulSubmissionPage
//  )

//  This scenario covers scenarios 1, 2, 6, 8 & 9 in the cis-ui-tests as the same pages are loaded ending at the Manage your CIS return subcontractor page.
  // Mechanics and database interaction are irrelevant when dealing with a stub.
  setup("successful-prepopulation", "SPR ").withRequests(
    getAuthPage,
    postManageAuthPage("Organisation", "EZ10400"),
    getSession,
    getManageFrontend,
    getSignIntoCISPage,
    getSignIntoCISRouting,
    getCisReturnDashboardPage,
    getClickSubcontractorsLink,
    getCheckSubcontractorRecordsPage("EZ10400"),
    postCheckSubcontractorRecordsPage("EZ10400"),
    getYourSubcontractors("EZ10400"),
    getStartPrepopulation("EZ10400"),
    getSuccessfulAutomaticSubcontractorUpdatePage,
    postSuccessfulAutomaticSubcontractorUpdatePage,
    getManageYourCISReturnSubcontractorPage
//    continue journey to add subcontractor, verify subcontractor or subcontractor list
  )

  //  This scenario covers scenarios 3, 4, 5 & 7 in the cis-ui-tests as the same pages are loaded ending at the Add subcontractor page.
  //  Mechanics and database interaction are irrelevant when dealing with a stub.
  setup("unsuccessful-prepopulation", "UPR ").withRequests(
    getAuthPage,
    postManageAuthPage("Organisation", "EZ10450"),
    getSession,
    getManageFrontend,
    getSignIntoCISPage,
    getSignIntoCISRouting,
    getCisReturnDashboardPage,
    getClickSubcontractorsLink,
    getCheckSubcontractorRecordsPage("EZ10450"),
    postCheckSubcontractorRecordsPage("EZ10450"),
    getYourSubcontractors("EZ10450"),
    getStartPrepopulation("EZ10450"),
    getUnsuccessfulAutomaticSubcontractorUpdatePage,
    postUnsuccessfulAutomaticSubcontractorUpdatePage
    // getAddContractorDetailsPage
    // TODO commented out above as no information on the URL change etc available
    //  continue journey to add subcontractor which is a terminal page at the moment
  )

  setup("add-individual-subcontractor", "AISP ").withRequests(
    getClickSubcontractorsLink,
    getManageYourCISReturnSubcontractorPage,
    getAddSubcontractor,
    getWhatTypeOfSubcontractorAreYouAdding,
    postWhatTypeOfSubcontractorAreYouAdding("soletrader"),
    getAddName,
    postAddName("tradingName"),
    getTradingName,
    postTradingName("Test Subcontractor Ltd"),
    getAddIndividualAddressPage,
    postAddIndividualAddressPage("true"),
    setIndividualAddressLookupNormalMode,
    getAddressLookupBegin,
    getAddressLookupCountryPicker,
    postAddressLookupCountryPicker("IE-Ireland"),
    getManuallyEnterAddressPage,
    postManuallyEnterAddressPage(
      "25 Oakley Road",
      "Flat 69",
      "",
      "City of Test",
      "SW22 42F",
      "IE"
    ),
    getReviewAddress,
    postReviewAddress,
    getReturnToIndividualNormalModeFrontendService,
    getAddIndividualContactDetailsPage,
    postAddIndividualContactDetailsPage("false"),
    getAddIndividualUtrPage,
    postAddIndividualUtrPage("true"),
    getIndividualUtrPage,
    postIndividualUtrPage("1234567895"),
    getAddIndividualNinoPage,
    postAddIndividualNinoPage("true"),
    getIndividualNinoPage,
    postIndividualNinoPage("AA123456C"),
    getAddIndividualWrnPage,
    postAddIndividualWrnPage("true"),
    getIndividualWrnPage,
    postIndividualWrnPage("12345678"),
    getIndividualCheckYourAnswersPage,
    getIndividualCheckYourAnswersPage,
    getChangeTradingNamePage,
    postChangeTradingNamePage("New Test Subcontractor Ltd"),
    getIndividualCheckYourAnswersPage,
    getChangeAddNamesPage,
    postChangeAddNamesPage("subcontractorName"),
    getChangeIndividualNamePage,
    postChangeIndividualNamePage("John", "Test", "Doe"),
    getIndividualCheckYourAnswersPage,
    getChangeIndividualNamePage,
    postChangeIndividualNamePage("Jane", "Tester", "Doe"),
    getIndividualCheckYourAnswersPage,
    setIndividualAddressLookupCheckMode,
    getAddressLookupBegin,
    getAddressLookupCountryPicker,
    postAddressLookupCountryPicker("GB-United_Kingdom"),
    getFindAddressWithPostcode,
    postFindAddressWithPostcode("AB21 3DE", "1243"),
    getManuallyEnterAddressPage,
    postManuallyEnterAddressPage(
      "123 Test Ave",
      "Flat 456",
      "",
      "Testing City",
      "AB21 3DE",
      "GB"
    ),
    getReviewAddress,
    postReviewAddress,
    getReturnToIndividualCheckModeFrontendService,
    getIndividualCheckYourAnswersPage,
    getChangeAddIndividualAddressPage,
    postChangeAddIndividualAddressPage("false"),
    getIndividualCheckYourAnswersPage,
    getChangeAddIndividualContactDetailsPage,
    postChangeAddIndividualContactDetailsPage("true"),
    getChangeIndividualContactMethodPage,
    postChangeIndividualContactMethodPage("email"),
    getChangeIndividualEmailAddressPage,
    postChangeIndividualEmailAddressPage("test@domain.co.uk"),
    getIndividualCheckYourAnswersPage,
    getChangeIndividualNinoPage,
    postChangeIndividualNinoPage("JJ123456A"),
    getIndividualCheckYourAnswersPage,
    getChangeAddIndividualNinoPage,
    postChangeAddIndividualNinoPage("false"),
    getIndividualCheckYourAnswersPage,
    getChangeIndividualUtrPage,
    postChangeIndividualUtrPage("7777777777"),
    getIndividualCheckYourAnswersPage,
    getChangeAddIndividualUtrPage,
    postChangeAddIndividualUtrPage("false"),
    getIndividualCheckYourAnswersPage,
    getChangeIndividualWrnPage,
    postChangeIndividualWrnPage("78789934"),
    getIndividualCheckYourAnswersPage,
    getChangeAddIndividualWrnPage,
    postChangeAddIndividualWrnPage("false"),
    getIndividualCheckYourAnswersPage,
    postIndividualCheckYourAnswersPage,
    getIndividualSubcontractorAddedPage
  )

  setup("add-partnership-subcontractor", "APSP").withRequests(
    getClickSubcontractorsLink,
    getManageYourCISReturnSubcontractorPage,
    getAddSubcontractor,
    getWhatTypeOfSubcontractorAreYouAdding,
    postWhatTypeOfSubcontractorAreYouAdding("partnership"),
    getPartnershipNamePage,
    postPartnershipNamePage("CIS Test Partnership"),
    getAddPartnershipAddressPage,
    postAddPartnershipAddressPage("true"),
    setPartnershipAddressLookupNormalMode,
    getAddressLookupBegin,
    getAddressLookupCountryPicker,
    postAddressLookupCountryPicker("GB-United_Kingdom"),
    getFindAddressWithPostcode,
    postFindAddressWithPostcode("AB1 2CD", "123"),
    getCannotFindAddress,
    getManuallyEnterAddressPage,
    postManuallyEnterAddressPage(
      "123 Test Drive",
      "Flat 456",
      "",
      "Manchester city",
      "AB1 2CD",
      "GB"
    ),
    getReviewAddress,
    postReviewAddress,
    getReturnToPartnershipNormalModeFrontendService,
    getAddPartnershipContactDetailsPage,
    postAddPartnershipContactDetailsPage(true),
    getPartnershipContactMethodPage,
    postPartnershipContactMethodPage("email"),
    getPartnershipEmailAddressPage,
    postPartnershipEmailAddressPage("john.doe@domainurl.com"),
    getAddPartnershipUTRPage,
    postAddPartnershipUTRPage("true"),
    getPartnershipUTRPage,
    postPartnershipUTRPage("1234567895"),
    getNominatedPartnerName,
    postNominatedPartnerName("Test Nominated Partner"),
    getAddNominatedPartnerUTRPage,
    postAddNominatedPartnerUTRPage("true"),
    getNominatedPartnerUTRPage,
    postNominatedPartnerUTRPage("9999999999"),
    getAddNominatedPartnerNinoPage,
    postAddNominatedPartnerNinoPage("true"),
    getNominatedPartnerNinoPage,
    postNominatedPartnerNinoPage("AA123456C"),
    getAddNominatedPartnerCrnPage,
    postAddNominatedPartnerCrnPage("true"),
    getNominatedPartnerCrnPage,
    postNominatedPartnerCrnPage("12345678"),
    getAddPartnershipWrnPage,
    postAddPartnershipWrnPage("true"),
    getPartnershipWrnPage,
    postPartnershipWrnPage("ref12345"),
    getPartnershipCheckYourAnswersPage,
    postPartnershipCheckYourAnswersPage,
    getChangePartnershipNamePage,
    postChangePartnershipNamePage("CIS Test Partnership Change"),
    getPartnershipCheckYourAnswersPage,
    setPartnershipAddressLookupCheckMode,
    setPartnershipAddressLookupCheckMode,
    getAddressLookupBegin,
    getAddressLookupCountryPicker,
    postAddressLookupCountryPicker("IE-Ireland"),
    getManuallyEnterAddressPage,
    postManuallyEnterAddressPage(
      "123 Test Drive Change",
      "Flat 456 Change",
      "Dublin city Change",
      "Dublin Change",
      "AB1 2CE",
      "IE"
    ),
    getReviewAddress,
    postReviewAddress,
    getReturnToPartnershipCheckModeFrontendService,
    getPartnershipCheckYourAnswersPage,
    getChangePartnershipEmailAddressPage,
    postChangePartnershipEmailAddressPage("john.doe.update@domainurl.com"),
    getPartnershipCheckYourAnswersPage,
    getChangePartnershipContactMethodPage,
    postChangePartnershipContactMethodPage("phone", "mobile"),
    getChangePartnershipPhoneNumberPage,
    postChangePartnershipPhoneNumberPage("01415008500"),
    getChangePartnershipMobileNumberPage,
    postChangePartnershipMobileNumberPage("+447543445421"),
    getPartnershipCheckYourAnswersPage,
    getPartnershipCheckYourAnswersPage,
    getChangePartnershipUTRPage,
    postChangePartnershipUTRPage("1234567896"),
    getPartnershipCheckYourAnswersPage,
    getChangeNominatedPartnerName,
    postChangeNominatedPartnerName("Test Nominated Partner Change"),
    getPartnershipCheckYourAnswersPage,
    getChangeNominatedPartnerUTRPage,
    postChangeNominatedPartnerUTRPage("9999999999"),
    getPartnershipCheckYourAnswersPage,
    getChangeNominatedPartnerNinoPage,
    postChangeNominatedPartnerNinoPage("AB123456D"),
    getPartnershipCheckYourAnswersPage,
    getChangeNominatedPartnerCrnPage,
    postChangeNominatedPartnerCrnPage("12345670"),
    getPartnershipCheckYourAnswersPage,
    getChangePartnershipWrnPage,
    postChangePartnershipWrnPage("ref54321"),
    getPartnershipCheckYourAnswersPage,
    getChangeAddPartnershipUTRPage,
    postChangeAddPartnershipUTRPage("false"),
    getPartnershipCheckYourAnswersPage,
    getChangeAddNominatedPartnerUTRPage,
    postChangeAddNominatedPartnerUTRPage("false"),
    getPartnershipCheckYourAnswersPage,
    getChangeAddNominatedPartnerNinoPage,
    postChangeAddNominatedPartnerNinoPage("false"),
    getPartnershipCheckYourAnswersPage,
    getChangeAddNominatedPartnerCrnPage,
    postChangeAddNominatedPartnerCrnPage("false"),
    getPartnershipCheckYourAnswersPage,
    getChangeAddPartnershipWrnPage,
    postChangeAddPartnershipWrnPage("false"),
    getPartnershipCheckYourAnswersPage,
    postPartnershipCheckYourAnswersPage,
    getPartnershipSubcontractorAddedPage
  )

  setup("add-company-subcontractor", "ACSP").withRequests(
    getClickSubcontractorsLink,
    getManageYourCISReturnSubcontractorPage,
    getAddSubcontractor,
    getWhatTypeOfSubcontractorAreYouAdding,
    postWhatTypeOfSubcontractorAreYouAdding("company"),
    getCompanyNamePage,
    postCompanyNamePage("CIS Test Company"),
    getAddCompanyAddressPage,
    postAddCompanyAddressPage("false"),
    getCompanyContactDetailsPage,
    postCompanyContactDetailsPage("false"),
    getAddCompanyUTRPage,
    postAddCompanyUTRPage("false"),
    getAddCompanyCrnPage,
    postAddCompanyCrnPage("false"),
    getAddCompanyWrnPage,
    postAddCompanyWrnPage("false"),
    getCompanyCheckYourAnswersPage,
    getChangeCompanyNamePage,
    postChangeCompanyNamePage("New CIS Test Company"),
    getCompanyCheckYourAnswersPage,
    getChangeAddCompanyAddressPage,
    postChangeAddCompanyAddressPage("true"),
    setCompanyAddressLookupCheckMode,
    getAddressLookupBegin,
    getAddressLookupCountryPicker,
    postAddressLookupCountryPicker("GB-United_Kingdom"),
    getFindAddressWithPostcode,
    postFindAddressWithPostcode("SW1 1SW", "5"),
    getCannotFindAddress,
    getManuallyEnterAddressPage,
    postManuallyEnterAddressPage(
      "125 Hill Street",
      "Flat 96",
      "Floor 7",
      "Test City",
      "SW1 1SW",
      "GB"
    ),
    getReviewAddress,
    postReviewAddress,
    getReturnToCompanyCheckModeFrontendService,
    getCompanyCheckYourAnswersPage,
    getChangeAddCompanyContactDetailsPage,
    postChangeAddCompanyContactDetailsPage("true"),
    getChangeCompanyContactMethodPage,
    postChangeCompanyContactMethodPage("mobile"),
    getChangeCompanyMobileNumberPage,
    postChangeCompanyMobileNumberPage("0987654321"),
    getCompanyCheckYourAnswersPage,
    getChangeAddCompanyUTRPage,
    postChangeAddCompanyUTRPage("true"),
    getChangeCompanyUTRPage,
    postChangeCompanyUTRPage("1234567895"),
    getCompanyCheckYourAnswersPage,
    getChangeAddCompanyCrnPage,
    postChangeAddCompanyCrnPage("true"),
    getChangeCompanyCrnPage,
    postChangeCompanyCrnPage("10000008"),
    getCompanyCheckYourAnswersPage,
    getChangeAddCompanyWrnPage,
    postChangeAddCompanyWrnPage("true"),
    getChangeCompanyWrnPage,
    postChangeCompanyWrnPage("123456780"),
    getCompanyCheckYourAnswersPage,
    postCompanyCheckYourAnswersPage,
    getCompanySubcontractorAddedPage
  )

  setup("add-trust-subcontractor", "ATSP").withRequests(
    getClickSubcontractorsLink,
    getManageYourCISReturnSubcontractorPage,
    getAddSubcontractor,
    getWhatTypeOfSubcontractorAreYouAdding,
    postWhatTypeOfSubcontractorAreYouAdding("trust"),
    getTrustNamePage,
    postTrustNamePage("CIS Test Trust"),
    getAddTrustAddressPage,
    postAddTrustAddressPage("false"),
    getTrustContactDetailsPage,
    postTrustContactDetailsPage("false"),
    getAddTrustUTRPage,
    postAddTrustUTRPage("false"),
    getAddTrustWrnPage,
    postAddTrustWrnPage("false"),
    getTrustCheckYourAnswersPage,
    getChangeTrustNamePage,
    postChangeTrustNamePage("CIS Test Trust Change"),
    getTrustCheckYourAnswersPage,
    getChangeAddTrustAddressPage,
    postChangeAddTrustAddressPage("true"),
    setTrustAddressLookupCheckMode,
    getAddressLookupBegin,
    getAddressLookupCountryPicker,
    postAddressLookupCountryPicker("IE-Ireland"),
    getManuallyEnterAddressPage,
    postManuallyEnterAddressPage(
      "123 Test Drive Change",
      "Flat 456 Change",
      "Dublin city Change",
      "Dublin Change",
      "AB1 2CE",
      "IE"
    ),
    getReviewAddress,
    postReviewAddress,
    getReturnToTrustCheckModeFrontendService,
    getTrustCheckYourAnswersPage,
    getChangeAddTrustContactDetailsPage,
    postChangeAddTrustContactDetailsPage("true"),
    getChangeTrustContactMethodPage,
    postChangeTrustContactMethodPage("email"),
    getChangeTrustEmailAddressPage,
    postChangeTrustEmailAddressPage("john.doe.update@hmrc.co.uk"),
    getTrustCheckYourAnswersPage,
    getChangeAddTrustWrnPage,
    postChangeAddTrustWrnPage("true"),
    getChangeTrustWrnPage,
    postChangeTrustWrnPage("ref54321"),
    getTrustCheckYourAnswersPage,
    getChangeAddTrustUTRPage,
    postChangeAddTrustUTRPage("true"),
    getChangeTrustUTRPage,
    postChangeTrustUTRPage("1234567895"),
    getTrustCheckYourAnswersPage,
    postTrustCheckYourAnswersPage,
    getTrustSubcontractorAddedPage
  )

  setup("verify-subcontractor", "VSP").withRequests(
    getVerifySubcontractor,
    getVerifyWhichSubcontractorPage,
    postVerifyWhichSubcontractorPage(),
    getReverifyExistingSubcontractorPage,
    postReverifyExistingSubcontractorPage(),
    getReverifySelectSubcontractorPage,
    postReverifySelectSubcontractorPage(),
    getCurrentSubcontractorsToVerify,
    getModifyVerificationBatch,
    getCheckVerificationBatchReadiness,
    getVerifyEmailConfirmationPage,
    postVerifyEmailConfirmationPage("differentEmail"),
    getVerifyEnterEmailConfirmationPage,
    postVerifyEnterEmailConfirmationPage("test@test.com"),
    getVerificationCheckYourAnswersPage,
    postVerificationCheckYourAnswersPage,
//    getSubmittingVerificationRequestPage,
//    getVerificationPollingPage,
    getVerificationRequestSubmittedPage
  )
  runSimulation()
}
