/*
 * Copyright 2023 HM Revenue & Customs
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package uk.gov.hmrc.perftests.cis.simulations

import io.gatling.core.scenario.Simulation
import uk.gov.hmrc.performance.simulation.PerformanceTestRunner
import uk.gov.hmrc.perftests.cis.requests.AuthRequests._
import uk.gov.hmrc.perftests.cis.requests.LandingPagesRequests._
import uk.gov.hmrc.perftests.cis.requests.NilMonthlyReturnRequests._
import uk.gov.hmrc.perftests.cis.requests.PrepopulationRequests._
import uk.gov.hmrc.perftests.cis.requests.StandardMonthlyReturnRequests._
import uk.gov.hmrc.perftests.cis.requests.SubcontractorRequests._
import uk.gov.hmrc.perftests.cis.requests.AddPartnershipSubcontractorRequests._

class CisSimulation extends Simulation with PerformanceTestRunner {

  setup("org-landing-pages", "OLP ").withRequests(
    getAuthPage,
    postManageAuthPage("Organisation", "EZ00100"),
    getSession,
    getManageFrontend,
    getSignIntoCISPage,
    getSignIntoCISRouting,
    getCisReturnDashboardPage
  )

  setup("agent-landing-pages", "ALP ").withRequests(
    getAuthPage,
    postManageAuthPage("Agent", "123456"),
    getSession,
    getManageFrontend,
    getSignIntoCISPage,
    getSignIntoCISRouting,
    getRetrieveClientList,
    getStartRetrieveClientList,
    getFileMonthlyCISReturnsUnfilteredListPage,
    postFileMonthlyCISReturnsSearchPage("CN", "UHD Contractor Control Group"),
    getClientFilteredViewFileMonthlyCISReturnPage,
    getClientCisReturnDashboardPage,
    getClickReturnDueLink,
    getManageYourCISReturenPage
  )

  setup("standard-monthly-return", "SMRP").withRequests(
    getFileYourMonthlyCISReturn,
    getWhichTaxMonthAndYearAreYouFilingAReturnFor,
    postWhichTaxMonthAndYearAreYouFilingAReturnFor,
    getSelectSubcontractors,
    getSelectAllSelectSubcontractors,
    getDeselectAllSelectSubcontractors,
    postSelectSubcontractors("31001", "31002"),
    getYouHaveUnverifiedSubcontractors,
    postYouHaveUnverifiedSubcontractors("false"),
    getHowMuchDidYouPayToFirstSubcontractorInTotal,
    postHowMuchDidYouPayToFirstSubcontractorInTotal("1000"),
    getHowMuchDidFirstSubcontractorPayInMaterialCosts,
    postHowMuchDidFirstSubcontractorPayInMaterialCosts("200"),
    getHowMuchTaxInTotalDidYouDeductFromFirstSubcontractor,
    postHowMuchTaxInTotalDidYouDeductFromFirstSubcontractor("25"),
    getCheckYourAnswersForFirstSubcontractor,
    getChangeHowMuchDidYouPayToFirstSubcontractorInTotal,
    postChangeHowMuchDidYouPayToFirstSubcontractorInTotal("2000"),
    getCheckYourAnswersForFirstSubcontractor,
    getChangeHowMuchDidFirstSubcontractorPayInMaterialCosts,
    postChangeHowMuchDidFirstSubcontractorPayInMaterialCosts("500"),
    getCheckYourAnswersForFirstSubcontractor,
    getChangeHowMuchTaxInTotalDidYouDeductFromFirstSubcontractor,
    postChangeHowMuchTaxInTotalDidYouDeductFromFirstSubcontractor("125"),
    getCheckYourAnswersForFirstSubcontractor,
    postCheckYourAnswersForFirstSubcontractor,
    getYouHaveAddedDetailsForASingleSubcontractor,
    getChangeFirstSubcontractorsDetails,
    getChangeHowMuchDidYouPayToFirstSubcontractorInTotalDetails,
    postChangeHowMuchDidYouPayToFirstSubcontractorInTotalDetails("5000"),
    getChangeFirstSubcontractorsDetails,
    getChangeHowMuchDidFirstSubcontractorPayInMaterialCostsDetails,
    postChangeHowMuchDidFirstSubcontractorPayInMaterialCostsDetails("1000"),
    getChangeFirstSubcontractorsDetails,
    getChangeHowMuchTaxInTotalDidYouDeductFromFirstSubcontractorDetails,
    postChangeHowMuchTaxInTotalDidYouDeductFromFirstSubcontractorDetails("250"),
    getChangeFirstSubcontractorsDetails,
    postChangeFirstSubcontractorsDetails,
    getYouHaveAddedDetailsForASingleSubcontractor,
    postYouHaveAddedDetailsForASingleSubcontractor("false"),
    getWhichSubcontractorDoYouNeedToAddPaymentDetailsFor,
    postWhichSubcontractorDoYouNeedToAddPaymentDetailsFor("2"),
    getHowMuchDidYouPayToSecondSubcontractorInTotal,
    postHowMuchDidYouPayToSecondSubcontractorInTotal("5000"),
    getHowMuchDidSecondSubcontractorPayInMaterialCosts,
    postHowMuchDidSecondSubcontractorPayInMaterialCosts("2000"),
    getHowMuchTaxInTotalDidYouDeductFromSecondSubcontractor,
    postHowMuchTaxInTotalDidYouDeductFromSecondSubcontractor("1000"),
    getCheckYourAnswersForSecondSubcontractor,
    postCheckYourAnswersForSecondSubcontractor,
    getYouHaveAddedDetailsFor2Subcontractors,
    getAreYouSureYouWantToRemoveFirstSubcontractor,
    postAreYouSureYouWantToRemoveFirstSubcontractor("true"),
    getYouHaveAddedDetailsForASingleSubcontractor,
    postYouHaveAddedDetailsForASingleSubcontractor("true"),
    getSummaryOfPaymentsMade,
    getDoYouConfirmTheInformationInThisReturnIsCorrect,
    postDoYouConfirmTheInformationInThisReturnIsCorrect("true"),
    getDeclarationOfEmploymentStatus,
    postDeclarationOfEmploymentStatus("false"),
    getDeclarationOfVerifiedStatus,
    postDeclarationOfVerifiedStatus("false"),
    getSubmitInactivityRequest,
    postSubmitInactivityRequest("false"),
    getDoYouWantConfirmationByEmailThatThisReturnHasBeenSuccessfullySubmitted,
    postDoYouWantConfirmationByEmailThatThisReturnHasBeenSuccessfullySubmitted("false"),
    getCheckYourAnswersBeforeSubmittingYourReturn,
    getChangeDeclarationOfEmploymentStatus,
    postChangeDeclarationOfEmploymentStatus("true"),
    getCheckYourAnswersBeforeSubmittingYourReturn,
    getChangeDeclarationOfVerifiedStatus,
    postChangeDeclarationOfVerifiedStatus("true"),
    getCheckYourAnswersBeforeSubmittingYourReturn,
    getChangeSubmitInactivityRequest,
    postChangeSubmitInactivityRequest("true"),
    getInactivityRequest,
    getCheckYourAnswersBeforeSubmittingYourReturn,
    getChangeDoYouWantConfirmationByEmailThatThisReturnHasBeenSuccessfullySubmitted,
    postChangeDoYouWantConfirmationByEmailThatThisReturnHasBeenSuccessfullySubmitted("true"),
    getEnterYourEmailAddress,
    postEnterYourEmailAddress("test123@test.com"),
    getCheckYourAnswersBeforeSubmittingYourReturn,
    postCheckYourAnswersBeforeSubmittingYourReturn,
    postSubmissionSendPage,
    getPollingPage,
    getPollingPage,
    postPollingPage,
    getSuccessfulSubmissionPage
  )

  setup("nil-monthly-return", "NMRP").withRequests(
    getFileYourNilReturnPage,
    getConfirmNilReturnPage,
    postConfirmNilReturnPage,
    getDoYouWantToSubmitAnInactivityRequestPage,
    postDoYouWantToSubmitAnInactivityRequestPage("option2"),
    getConfirmEmailAddressPage,
    postConfirmEmailAddressPage("tester.test@test.com"),
    getDeclarationPage,
    postDeclarationPage("confirmed"),
    getMNRFCheckYourAnswersPage,
    getChangeDoYouWantToSubmitAnInactivityRequestPage,
    postChangeDoYouWantToSubmitAnInactivityRequestPage("option1"),
    getInactivityWarningPage,
    postInactivityWarningPage,
    getMNRFCheckYourAnswersPage,
    getChangeConfirmEmailAddressPage,
    postChangeConfirmEmailAddressPage("Submissionsuccessful@test.com"),
    getMNRFCheckYourAnswersPage,
    postMNRFCheckYourAnswersPage,
    postSubmissionSendPage,
    getPollingPage,
    getPollingPage,
    postPollingPage,
    getSuccessfulSubmissionPage
  )

  setup("add-sole-trader-subcontractor", "ASTP ").withRequests(
    getClickSubcontractorsLink,
    getManageYourCISReturnSubcontractorPage,
    getAddSubcontractor,
    getWhatTypeOfSubcontractorAreYouAdding,
    postWhatTypeOfSubcontractorAreYouAdding("soletrader"),
    getDoesTheSubcontractorUseATradingName,
    postDoesTheSubcontractorUseATradingName("true"),
    getWhatIsTheSubcontractorsTradingName,
    postWhatIsTheSubcontractorsTradingName("Test Subcontractor Ltd"),
    getDoYouWantToAddTheSubcontractorsAddress,
    postDoYouWantToAddTheSubcontractorsAddress("true"),
    getWhatIsTheSubcontractorsAddress,
    postWhatIsTheSubcontractorsAddress("123 Test Ave", "", "Testing City", "United Kingdom", "AB1 2CD"),
    getDoYouHaveANationalInsuranceNumber,
    postDoYouHaveANationalInsuranceNumber("true"),
    getWhatIsTheSubcontractorsNationalInsuranceNumber,
    postWhatIsTheSubcontractorsNationalInsuranceNumber("AA123456C"),
    getDoYouHaveAUniqueTaxpayerReference,
    postDoYouHaveAUniqueTaxpayerReference("true"),
    getWhatIsTheSubcontractorsUniqueTaxpayerReference,
    postWhatIsTheSubcontractorsUniqueTaxpayerReference("1111111111"),
    getDoYouHaveAWorksReferenceNumber,
    postDoYouHaveAWorksReferenceNumber("true"),
    getWhatIsTheWorksReferenceNumber,
    postWhatIsTheWorksReferenceNumber("12345678"),
    getDoYouWantToAddTheSubcontractorsContactDetails,
    postDoYouWantToAddTheSubcontractorsContactDetails("true"),
    getSubcontractorsContactDetails,
    postSubcontractorsContactDetails("Test123@test.com", "01234567890"),
    getSubcontractorCheckYourAnswersPage,
    getChangeWhatTypeOfSubcontractorAreYouAdding,
    postChangeWhatTypeOfSubcontractorAreYouAdding("soletrader"),
    getSubcontractorCheckYourAnswersPage,
    getChangeWhatIsTheSubcontractorsTradingName,
    postChangeWhatIsTheSubcontractorsTradingName("New Test Subcontractor Ltd"),
    getSubcontractorCheckYourAnswersPage,
    getChangeDoesTheSubcontractorUseATradingName,
    postChangeDoesTheSubcontractorUseATradingName("false"),
    getChangeWhatIsTheSubcontractorsName,
    postChangeWhatIsTheSubcontractorsName("John", "Test", "Doe"),
    getSubcontractorCheckYourAnswersPage,
    getChangeWhatIsTheSubcontractorsName,
    postChangeWhatIsTheSubcontractorsName("Jane", "Tester", "Doe"),
    getSubcontractorCheckYourAnswersPage,
    getChangeWhatIsTheSubcontractorsAddress,
    postChangeWhatIsTheSubcontractorsAddress("123 Test Ave", "Flat 456", "Testing City", "United Kingdom", "AB21 3DE"),
    getSubcontractorCheckYourAnswersPage,
    getChangeDoYouWantToAddTheSubcontractorsAddress,
    postChangeDoYouWantToAddTheSubcontractorsAddress("false"),
    getSubcontractorCheckYourAnswersPage,
    getChangeWhatIsTheSubcontractorsNationalInsuranceNumber,
    postChangeWhatIsTheSubcontractorsNationalInsuranceNumber("JJ123456A"),
    getSubcontractorCheckYourAnswersPage,
    getChangeDoYouHaveANationalInsuranceNumber,
    postChangeDoYouHaveANationalInsuranceNumber("false"),
    getSubcontractorCheckYourAnswersPage,
    getChangeWhatIsTheSubcontractorsUniqueTaxpayerReference,
    postChangeWhatIsTheSubcontractorsUniqueTaxpayerReference("2222222222"),
    getSubcontractorCheckYourAnswersPage,
    getChangeDoYouHaveAUniqueTaxpayerReference,
    postChangeDoYouHaveAUniqueTaxpayerReference("false"),
    getSubcontractorCheckYourAnswersPage,
    getChangeWhatIsTheWorksReferenceNumber,
    postChangeWhatIsTheWorksReferenceNumber("78789934"),
    getSubcontractorCheckYourAnswersPage,
    getChangeDoYouHaveAWorksReferenceNumber,
    postChangeDoYouHaveAWorksReferenceNumber("false"),
    getSubcontractorCheckYourAnswersPage,
    getChangeSubcontractorsContactDetails,
    postChangeSubcontractorsContactDetails("doe.test@testurl.com", "449876543210"),
    getSubcontractorCheckYourAnswersPage,
    getChangeDoYouWantToAddTheSubcontractorsContactDetails,
    postChangeDoYouWantToAddTheSubcontractorsContactDetails("false"),
    getSubcontractorCheckYourAnswersPage
  )

//  This scenario covers scenarios 1, 2, 6, 8 & 9 in the cis-ui-tests as the same pages are loaded ending at the Manage your CIS return subcontractor page.
  // Mechanics and database interaction are irrelevant when dealing with a stub.
  setup("successful-prepopulation", "SPR ").withRequests(
    getAuthPage,
    postManageAuthPage("Organisation", "EZ10400"),
    getSession,
    getManageFrontend,
    getSignIntoCISPage,
    getSignIntoCISRouting,
    getCisReturnDashboardPage,
    getClickSubcontractorsLink,
    getCheckSubcontractorRecordsPage("EZ10400"),
    postCheckSubcontractorRecordsPage("EZ10400"),
    getYourSubcontractors("EZ10400"),
    getStartPrepopulation("EZ10400"),
    getSuccessfulAutomaticSubcontractorUpdatePage,
    postSuccessfulAutomaticSubcontractorUpdatePage,
    getManageYourCISReturnSubcontractorPage
//    continue journey to add subcontractor, verify subcontractor or subcontractor list
  )

  //  This scenario covers scenarios 3, 4, 5 & 7 in the cis-ui-tests as the same pages are loaded ending at the Add subcontractor page.
  //  Mechanics and database interaction are irrelevant when dealing with a stub.
  setup("unsuccessful-prepopulation", "UPR ").withRequests(
    getAuthPage,
    postManageAuthPage("Organisation", "EZ10450"),
    getSession,
    getManageFrontend,
    getSignIntoCISPage,
    getSignIntoCISRouting,
    getCisReturnDashboardPage,
    getClickSubcontractorsLink,
    getCheckSubcontractorRecordsPage("EZ10450"),
    postCheckSubcontractorRecordsPage("EZ10450"),
    getYourSubcontractors("EZ10450"),
    getStartPrepopulation("EZ10450"),
    getUnsuccessfulAutomaticSubcontractorUpdatePage,
    postUnsuccessfulAutomaticSubcontractorUpdatePage,
    getAddContractorDetailsPage
    //    continue journey to add subcontractor which is a terminal page at the moment
  )

  setup("add-partnership-subcontractor", "APSP").withRequests(
    getClickSubcontractorsLink,
    getManageYourCISReturnSubcontractorPage,
    getAddSubcontractor,
    getWhatTypeOfSubcontractorAreYouAdding,
    postWhatTypeOfSubcontractorAreYouAdding("partnership"),
    getPartnershipNamePage,
    postPartnershipNamePage("CIS Test Partnership"),
    getAddPartnershipAddressPage,
    postAddPartnershipAddressPage("true"),
    getPartnershipAddressPage,
    postPartnershipAddressPage(
      "123 Test Drive",
      "Flat 456",
      "Manchester city",
      "Greater Manchester",
      "AB1 2CD",
      "United Kingdom"
    ),
    getPartnershipContactMethodPage,
    postPartnershipContactMethodPage("email"),
    getPartnershipEmailAddressPage,
    postPartnershipEmailAddressPage("john.doe@domainurl.com"),
    getAddPartnershipUTRPage,
    postAddPartnershipUTRPage("true"),
    getPartnershipUTRPage,
    postPartnershipUTRPage("1234567895"),
    getNominatedPartnerName,
    postNominatedPartnerName("Test Nominated Partner"),
    getAddNominatedPartnerUTRPage,
    postAddNominatedPartnerUTRPage("true"),
    getNominatedPartnerUTRPage,
    postNominatedPartnerUTRPage("9999999999"),
    getAddNominatedPartnerNinoPage,
    postAddNominatedPartnerNinoPage("true"),
    getNominatedPartnerNinoPage,
    postNominatedPartnerNinoPage("AA123456C"),
    getAddNominatedPartnerCrnPage,
    postAddNominatedPartnerCrnPage("true"),
    getNominatedPartnerCrnPage,
    postNominatedPartnerCrnPage("12345678"),
    getAddPartnershipWrnPage,
    postAddPartnershipWrnPage("true"),
    getPartnershipWrnPage,
    postPartnershipWrnPage("ref12345"),
    getPartnershipCheckYourAnswersPage,
    postPartnershipCheckYourAnswersPage,
    getChangePartnershipNamePage,
    postChangePartnershipNamePage("CIS Test Partnership Change"),
    getPartnershipCheckYourAnswersPage,
    getChangePartnershipAddressPage,
    postChangePartnershipAddressPage(
      "123 Test Drive Change",
      "Flat 456 Change",
      "Dublin city Change",
      "Dublin Change",
      "AB1 2CE",
      "Ireland"
    ),
    getPartnershipCheckYourAnswersPage,
    getChangePartnershipEmailAddressPage,
    postChangePartnershipEmailAddressPage("john.doe.update@domainurl.com"),
    getPartnershipCheckYourAnswersPage,
    getChangePartnershipContactMethodPage,
    postChangePartnershipContactMethodPage("phone"),
    getChangePartnershipPhoneNumberPage,
    postChangePartnershipPhoneNumberPage("01415008500"),
    getPartnershipCheckYourAnswersPage,
    getChangePartnershipContactMethodPage,
    postChangePartnershipContactMethodPage("mobile"),
    postChangePartnershipMobileNumberPage("+447543445421"),
    getPartnershipCheckYourAnswersPage,
    getChangePartnershipContactMethodPage,
    postChangePartnershipContactMethodPage("noDetails"),
    getPartnershipCheckYourAnswersPage,
    getChangePartnershipUTRPage,
    postChangePartnershipUTRPage("1234567896"),
    getPartnershipCheckYourAnswersPage,
    getChangeNominatedPartnerName,
    postChangeNominatedPartnerName("Test Nominated Partner Change"),
    getPartnershipCheckYourAnswersPage,
    getChangeNominatedPartnerUTRPage,
    postChangeNominatedPartnerUTRPage("9999999999"),
    getPartnershipCheckYourAnswersPage,
    getChangeNominatedPartnerNinoPage,
    postChangeNominatedPartnerNinoPage("AB123456D"),
    getPartnershipCheckYourAnswersPage,
    getChangeNominatedPartnerCrnPage,
    postChangeNominatedPartnerCrnPage("12345670"),
    getPartnershipCheckYourAnswersPage,
    getChangePartnershipWrnPage,
    postChangePartnershipWrnPage("ref54321"),
    getPartnershipCheckYourAnswersPage,
    getChangeAddPartnershipUTRPage,
    postChangeAddPartnershipUTRPage("false"),
    getPartnershipCheckYourAnswersPage,
    getChangeAddNominatedPartnerUTRPage,
    postChangeAddNominatedPartnerUTRPage("false"),
    getPartnershipCheckYourAnswersPage,
    getChangeAddNominatedPartnerNinoPage,
    postChangeAddNominatedPartnerNinoPage("false"),
    getPartnershipCheckYourAnswersPage,
    getChangeAddNominatedPartnerCrnPage,
    postChangeAddNominatedPartnerCrnPage("false"),
    getPartnershipCheckYourAnswersPage,
    getChangeAddPartnershipWrnPage,
    postChangeAddPartnershipWrnPage("false"),
    getPartnershipCheckYourAnswersPage,
    postPartnershipCheckYourAnswersPage,
    getPartnershipSubcontractorAddedPage
  )
  runSimulation()
}
